name: discord_webhook_twitter_tracker
description: An application that streams twitter using their API and puts it on a discord channel with webhooks.
version: 1.0.0
# homepage: https://github.com/alvarogfn/discord-webhook-twitter-tracker

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  dio: ^4.0.4
  dotenv: ^3.0.0
  translator: ^0.1.7

dev_dependencies:
  lints: ^1.0.0
